### ISSUE TITLE
gpg.sh error

### ISSUE THREAD

**Issue by hithwen** [DataDog/yubikey#76]
```
❯ ./gpg.sh
OS detected is macos
Is it correct ? (y|N)y
env.sh: line 34: ${OS,,}: bad substitution
```
Running in BigSur

```
sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by hithwen** [comment]
I think solution is to replace line 34 of env.sh for `case "$OS" in`

**Comment by daisukixci** [comment]
Hi @hithwen, 

Thanks for taking the time to report.
 
It's a known "issue" and the solution is here https://github.com/DataDog/yubikey/blob/master/docs/troubleshooting.md#bad-substitution. The issue is that you use an outdated bash version (probably the default macos one).

Also, since you are not the only person who have that issue, we did https://github.com/DataDog/yubikey/pull/74 which is under review which will remove the necessity to use a bash version equal or above 4 even though we recommend you to update your bash version and to not use the macos version.

Thank you.
